"""empty message

Revision ID: 02a154264314
Revises: f8159c65f1be
Create Date: 2019-01-30 20:28:35.782901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a154264314'
down_revision = 'f8159c65f1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('primary_image', sa.String(length=550), nullable=True))
    op.drop_column('tags', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('image', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('tags', 'primary_image')
    # ### end Alembic commands ###
