"""empty message

Revision ID: 56d294034b42
Revises: 6f59f4fa9f25
Create Date: 2019-01-30 20:07:11.319222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56d294034b42'
down_revision = '6f59f4fa9f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('assets', sa.Column('url', sa.String(length=1000), nullable=False))
    op.drop_column('assets', 'data')
    op.add_column('tags', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('tags', sa.Column('image_id', sa.Integer(), nullable=False))
    op.add_column('tags', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tags', 'assets', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tags', 'creation_date')
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'assets', ['avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    op.add_column('tags', sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'owner_id')
    op.drop_column('tags', 'image_id')
    op.drop_column('tags', 'created')
    op.add_column('assets', sa.Column('data', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('assets', 'url')
    op.drop_column('assets', 'created')
    # ### end Alembic commands ###
